#! /bin/bash
#SBATCH -A vpaschal
#SBATCH -p standard
#SBATCH -t 0:10:00
#SBATCH -N 1 -n 2
#SBATCH 
#SBATCH -J tov2-0001
#SBATCH --mail-type=ALL
#SBATCH --mail-user=gabrielebozzola@email.arizona.edu
#SBATCH -o /xdisk/vpaschal/mig2020/rsgrps/vpaschal/gabrielebozzola/sims/tov2/output-0001/tov2.out
#SBATCH -e /xdisk/vpaschal/mig2020/rsgrps/vpaschal/gabrielebozzola/sims/tov2/output-0001/tov2.err
cd /home/u20/gabrielebozzola/NewCactus/Cactus
/home/u20/gabrielebozzola/NewCactus/Cactus/repos/simfactory2/bin/sim run tov2 --machine=puma --restart-id=1 
